### ISSUE TITLE
 RsSt-ShenzhenUV链接失效

### ISSUE THREAD

**Issue by gloryofroad** [RunyuFan/FusionMixer-TGRS-2022#1]
RsSt-ShenzhenUV链接失效，可以重新发一份吗

**Comment by RunyuFan** [comment]
链接:https://pan.baidu.com/s/1ChKks1_FxIjPe2V64MgZ0w?pwd=bt9q 
提取码:bt9q

**Comment by gloryofroad** [comment]
非常感谢！




星月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RunyuFan/FusionMixer-TGRS-2022"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月7日(星期二) 下午2:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RunyuFan/FusionMixer-TGRS-2022]  RsSt-ShenzhenUV链接失效 (Issue #1)





 
链接:https://pan.baidu.com/s/1ChKks1_FxIjPe2V64MgZ0w?pwd=bt9q&nbsp;
 提取码:bt9q

**Comment by gsenxu** [comment]
RsSt-ShenzhenUV 失效了，可以再发个下载链接吗

**Comment by RunyuFan** [comment]
> RsSt-ShenzhenUV 失效了，可以再发个下载链接吗

通过百度网盘分享的文件：樊润宇-RsSt-ShenzhenUV数据集.zip
链接：https://pan.baidu.com/s/1OpCEGqiqLaEivMH6Lq2mCA?pwd=mqnp 
提取码：mqnp 
--来自百度网盘超级会员V4的分享
