### ISSUE TITLE
RsSt-ShenzhenUV链接失效

### ISSUE THREAD

**Issue by zhangyong0919** [RunyuFan/FusionMixer-TGRS-2022#2]
您好，可以再发一次链接吗。

**Comment by RunyuFan** [comment]
> 您好，可以再发一次链接吗。

通过百度网盘分享的文件：樊润宇-RsSt-ShenzhenUV数据集.zip
链接：https://pan.baidu.com/s/1OpCEGqiqLaEivMH6Lq2mCA?pwd=mqnp 
提取码：mqnp 
--来自百度网盘超级会员V4的分享

**Comment by zhangyong0919** [comment]
非常感谢。

**Comment by RunyuFan** [comment]
> 您好，可以再发一次链接吗。

通过百度网盘分享的文件：樊润宇-RsSt-ShenzhenUV数据集.zip
链接：https://pan.baidu.com/s/1ShWdyU6TaZ85WNLLfAasTw?pwd=rx35 
提取码：rx35 
--来自百度网盘超级会员V4的分享
